/* COMMAND TO CREATE THE DATASET */
Data temp;
/* COMMAND TO CREATE THE VARIABLES */
INPUT ID NAME $ SALARY DEPARTMENT $;
COMM=SALARY*0.25;
/* COMMAND TO CREATE THE LABELS FOR A SPECIFIC COLUMNS */
LABEL ID = 'EMPLOYEE ID' COMM='COMMISION';
/* COMMAND TO ADD ROWS IN THE DATASET */
DATALINES;
1 RICK 623.3 IT
2 DAN 515.2 OPERATIONS
3 MICHELLE 611 IT
4 RYAN 729 HR
5 GARY 843.25 FINANCE
6 NINA 578 IT
7 SIMON 632.8 OPERATIONS
;
RUN;

PROC PRINT DATA=temp;
RUN;

PROC MEANS;
RUN;

PROC PRINT DATA=temp;
WHERE SALARY>700;
RUN;

DATA EMP;
